### ISSUE TITLE
"embedded one to many" doesn't work

### ISSUE THREAD

**Issue by lgs** [joshuabowers/search_magic#23]
I have a User model

<pre>
  class User
    include Mongoid::Document
    field :name

    embeds_many :watchlists
  end
</pre>

which embeds many Watchlist(s)

<pre>
  class Watchlist
    include Mongoid::Document
    include SearchMagic

    field :description

    embedded_in :user
    search_on :description
  end
</pre>

But when I look for a string in description, which I know it exsist,  I cannot find anything :

<pre>
  ruby-1.9.2-p290 :001 > User.all.map do |user|
  ruby-1.9.2-p290 :002 >         user.watchlists.search_for("It's a presentation framework based on").first
  ruby-1.9.2-p290 :003?> end
  MONGODB gitwatch_dev['system.namespaces'].find({})
  MONGODB gitwatch_dev['users'].find({})
   => [nil] 
</pre>

specifiing the field searched it's the same :

<pre>
  ruby-1.9.2-p290 :004 > User.all.map do |user|
  ruby-1.9.2-p290 :005 >          user.watchlists.search_for("description:'a presentation framework based on'").first
  ruby-1.9.2-p290   :006?> end
  MONGODB gitwatch_dev['users'].find({})
   => [nil] 
  ruby-1.9.2-p290 :007 > 
</pre>

I tried also with ather fields, no success. Do I miss something ?

**Comment by joshuabowers** [comment]
Hmm... this is a rather bizarre issue. The problem seems to be stemming from how mongoid is searching an array field of an embedded document. For a top-level document, it is possible to compare the contents of an array field against an array of regexs; this is what search_for essentially does. This does not seem to be working properly for embedded documents (at least not in either Mongoid 2.3.4 or 2.4.1).

The returned criteria should have a selector set to something like:

``` ruby
:searchable_values => { "$all" => [/^([^:]+:)?.*presentation/i] }
```

This type of query should normally work: all it does is specify that a matching document should have values in searchable_values which are all consistent with the specified regex.

My tests indicate that the searchable_values of Watchlist instances are, in fact, being correctly filled with data. Can you verify that this is the case? I.e. something like the following should be true:

``` ruby
User.first.watchlists.first.searchable_values # should be something like [..., "description:presentation", "description:framework", ...]
```

If the data is there, then the criteria I'm generating is either invalid in some respect or not supported by mongoid; if the latter, it might be something fixable on the Mongoid end, in which case I'll be making an issue on mongoid's issue tracker.

In the meantime, you might consider simply making User searchable, either fully or on watchlists. While this would not provide the exact type of semantics you were going for (i.e., you would get all users which have watchlists which match a given description, rather than all watchlists, of a given user, which match a given description), it might prove ever so slightly beneficial. While not available in 0.2.0, future versions should have an instance method called [values_matching](https://github.com/joshuabowers/search_magic/issues/18), which returns those entries in searchable_values which match the provided search pattern. While not an ideal solution, you could use this to winnow the watchlists properly.

**Comment by lgs** [comment]
I tried the suggested verification but is empty :

<pre>
ruby-1.9.2-p290 :001 > User.first.watchlists.first.searchable_values
MONGODB gitwatch_dev['system.namespaces'].find({})
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => [] 
ruby-1.9.2-p290 :002 > 
</pre>


<pre>
ruby-1.9.2-p290 :025 > User.first.watchlists.size
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => 1667 
ruby-1.9.2-p290 :026 > 
</pre>


<pre>
ruby-1.9.2-p290 :039 > Watchlist.searchables.keys
 => [:description] 

ruby-1.9.2-p290 :053 > User.first.watchlists.searchables.keys
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => [:description] 
ruby-1.9.2-p290 :054 > 
</pre>


<pre>
ruby-1.9.2-p290 :040 > Watchlist.searchable_values
NoMethodError: undefined method `searchable_values' for Watchlist:Class
    from (irb):40
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands/console.rb:45:in `start'
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands/console.rb:8:in `start'
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
ruby-1.9.2-p290 :041 >
</pre>


search_for  methods :

<pre>
ruby-1.9.2-p290 :058 > User.first.watchlists.search_for("HTML, CSS, and JS toolkit from Twitter")
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => #<Mongoid::Criteria
  selector: {:searchable_values=>{"$all"=>[/([^:]+:)?.*HTML/i, /([^:]+:)?.*CSS/i, /([^:]+:)?.*and/i, /([^:]+:)?.*JS/i, /([^:]+:)?.*toolkit/i, /([^:]+:)?.*from/i, /([^:]+:)?.*Twitter/i]}},
  options:  {},
  class:    Watchlist,
  embedded: true>
 
ruby-1.9.2-p290 :059 > User.first.watchlists.search_for("HTML, CSS, and JS toolkit from Twitter").first
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => nil 
ruby-1.9.2-p290 :060 > 

ruby-1.9.2-p290 :062 > User.first.watchlists.first.search_for("HTML, CSS, and JS toolkit from Twitter")
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
NoMethodError: undefined method `search_for' for #<Watchlist:0xd646b8c>
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/activemodel-3.1.3/lib/active_model/attribute_methods.rb:385:in `method_missing'
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/mongoid-2.3.4/lib/mongoid/attributes.rb:184:in `method_missing'
    from (irb):62
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands/console.rb:45:in `start'
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands/console.rb:8:in `start'
    from /home/lsoave/.rvm/gems/ruby-1.9.2-p290@rails-3.1.3/gems/railties-3.1.3/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
ruby-1.9.2-p290 :063 > 

ruby-1.9.2-p290 :064 > User.first.watchlists.search_for("description:'HTML, CSS, and JS toolkit from Twitter'").first
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => nil 
ruby-1.9.2-p290 :065 > User.first.watchlists.search_for("description:'HTML, CSS, and JS toolkit from Twitter'")
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
 => #<Mongoid::Criteria
  selector: {:searchable_values=>{"$all"=>[/description:.*HTML/i, /description:.*CSS/i, /description:.*and/i, /description:.*JS/i, /description:.*toolkit/i, /description:.*from/i, /description:.*Twitter/i]}},
  options:  {},
  class:    Watchlist,
  embedded: true>
 
ruby-1.9.2-p290 :066 > 

</pre>


A note on the env:

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ mongod --version
db version v1.6.5, pdfile version 4.5
Sun Jan 22 20:45:17 git version: 0eb017e9b2828155a67c5612183337b89e12e291
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>


<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ grep mongoid  Gemfile.lock
  remote: https://github.com/lgs/mongoid_taggable_with_context.git
    mongoid_taggable_with_context (0.7.2)
      mongoid (~> 2.3.0)
    mongoid (2.3.4)
    mongoid-rspec (1.4.4)
      mongoid (~> 2.0)
      mongoid (>= 2.0.0)
  mongoid (~> 2.3.4)
  mongoid-rspec
  mongoid_taggable_with_context!
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>


<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ grep search_magic Gemfile.lock
    search_magic (0.2.0)
  search_magic
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>


<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ rvm gemset list

gemsets for ruby-1.9.2-p290 (found in /home/lsoave/.rvm/gems/ruby-1.9.2-p290)
   global
=> rails-3.1.3

lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>

**Comment by lgs** [comment]
UPDATE :

upgrading to MongoDB  2.0.2  and  MongoID  2.4.2,  
running db from scratch,     nothing changes.

<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ mongod --version
db version v2.0.2, pdfile version 4.5
Mon Jan 23 00:09:07 git version: 514b122d308928517f5841888ceaa4246a7f18e3
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>


<pre>
lsoave@ubuntu:~/rails/github/gitwatcher$ grep mongoid Gemfile.lock
    mongoid (2.4.2)
    mongoid-rspec (1.4.4)
      mongoid (~> 2.0)
    mongoid_taggable_with_context (0.8.0)
      mongoid (>= 2.0.0)
      mongoid (>= 2.0.0)
  mongoid (= 2.4.2)
  mongoid-rspec
  mongoid_taggable_with_context (= 0.8.0)
lsoave@ubuntu:~/rails/github/gitwatcher$ 
</pre>

**Comment by joshuabowers** [comment]
Thanks for the detailed information, lgs! After posting my message earlier, I went ahead and posted an [issue](https://github.com/mongoid/mongoid/issues/1626) on the mongoid issue tracker that seemed to adhere to the behavior I was witnessing. If, indeed, that was the source of the overall issue, this particular bug should likely be addressed as soon as a version of mongoid >= 2.4.3 is released. 

About your information:

It's rather odd that the searchable_values data is not present. There are two reasons I can think of for why this would be true:
1. You added SearchMagic into your project well after having data in the watchlists;
2. You build your watchlists and save your users, rather than creating your watchlists.

The first item could be very simply solved: iterate over all watchlists in your system and resave them; this would then trigger the appropriate callbacks provided by SearchMagic on those classes.

The second is due to an optimization present in mongoid, which causes callbacks to only be invoked on the document which invokes a save. You can get around this by one of three methodologies:
1. Always save at the level of the searchable object;
2. Turn on [cascading callbacks](http://mongoid.org/docs/relations/embedded/1-n.html), and save at the level of the root-level document;
3. Make User searchable; each model which includes SearchMagic keeps track of its inverse searchables; these are the searchable models which search the current document. When a document is saved, it automatically updates anything which touches it.

**Comment by lgs** [comment]
Good news, it works; you've been invaluable.

First,  I added `gem "mongoid", :git => 'https://github.com/mongoid/mongoid.git'` to Gemfile, because it pull the regex fix, about the issue you opened on mongoid ( https://github.com/mongoid/mongoid/issues/1626 ).

<pre>
+GIT
+  remote: https://github.com/mongoid/mongoid.git
+  revision: 76dc254ac17fd14fb758f23ee5db35eb05398cb6
+  specs:
+    mongoid (3.0.0)
+      activemodel (~> 3.1)
+      mongo (~> 1.3)
+      tzinfo (~> 0.3.22)
+
</pre>


Second, I iterate over all watchlists in the system and resave them :

<pre>
User.all.map do |user|
    user.watchlists.all.map do |w|
        w.save
    end
end
</pre>


Now I can get the values :

<pre>
ruby-1.9.2-p290 :035 >    User.first.watchlists.first.searchable_values
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
=> ["description:grit", "description:gives", "description:you", "description:object", "description:oriented", "description:read", "description:write", "description:access", "description:to", "description:git", "description:repositories", "description:via", "description:ruby"]
ruby-1.9.2-p290 :036 >
</pre>


... and I can query :

<pre>
ruby-1.9.2-p290 :098 > User.first.watchlists.search_for("HTML, CSS, and JS toolkit from Twitter").all.map{|l|l}
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
=> [#<Watchlist _id: 4f1c95fb1d41c80ff200063f, _type: nil, searchable_values: ["description:html", "description:css", "description:and", "description:js", "description:toolkit", "description:from", "description:twitter"], arrangeable_values: {"description"=>"HTML, CSS, and JS toolkit from Twitter"}, html_url: "https://github.com/twitter/bootstrap", description: "HTML, CSS, and JS toolkit from Twitter", fork_: false, forks: 2735, watchers: 15056, created_at: 2011-07-29 21:19:00 UTC, pushed_at: 2012-01-22 21:01:29 UTC, avatar_url: "https://secure.gravatar.com/avatar/74e977ae0a10f06057a119eef30c6660?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-orgs.png", tags: "all", tags_array: []>]
ruby-1.9.2-p290 :099 >
</pre>


... recombining or permuting :

<pre>
ruby-1.9.2-p290 :101 > User.first.watchlists.search_for(" JS toolkit HTML Twitter CSS ").all.map{|l|l}
MONGODB gitwatch_dev['users'].find({}).limit(-1).sort([[:_id, :asc]])
=> [#<Watchlist _id: 4f1c95fb1d41c80ff200063f, _type: nil, searchable_values: ["description:html", "description:css", "description:and", "description:js", "description:toolkit", "description:from", "description:twitter"], arrangeable_values: {"description"=>"HTML, CSS, and JS toolkit from Twitter"}, html_url: "https://github.com/twitter/bootstrap", description: "HTML, CSS, and JS toolkit from Twitter", fork_: false, forks: 2735, watchers: 15056, created_at: 2011-07-29 21:19:00 UTC, pushed_at: 2012-01-22 21:01:29 UTC, avatar_url: "https://secure.gravatar.com/avatar/74e977ae0a10f06057a119eef30c6660?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-orgs.png", tags: "all", tags_array: []>]
ruby-1.9.2-p290 :102 >
</pre>


Many Thanks.

**Comment by joshuabowers** [comment]
Glad to see that worked for you!
